/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticoRouteRouteImport } from './routes/diagnostico/route'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DiagnosticoIndexRouteImport } from './routes/diagnostico/index'
import { Route as DiagnosticoAnexosRouteImport } from './routes/diagnostico/anexos'
import { Route as DiagnosticoCalorRouteImport } from './routes/diagnostico/calor'
import { Route as DiagnosticoIdentificacaoRouteImport } from './routes/diagnostico/identificacao'
import { Route as DiagnosticoPendenciasRouteImport } from './routes/diagnostico/pendencias'
import { Route as DiagnosticoProcuracaoRouteImport } from './routes/diagnostico/procuracao'
import { Route as DiagnosticoRevisaoRouteImport } from './routes/diagnostico/revisao'
import { Route as DiagnosticoRiscosRouteImport } from './routes/diagnostico/riscos'
import { Route as DiagnosticoSituacaoRouteImport } from './routes/diagnostico/situacao'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as DiagnosticoEnviadoProtocoloRouteImport } from './routes/diagnostico/enviado.$protocolo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRouteRoute = DiagnosticoRouteRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoIndexRoute = DiagnosticoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnosticoRouteRoute,
} as any)
const DiagnosticoAnexosRoute = DiagnosticoAnexosRouteImport.update({
  id: '/anexos',
  path: '/anexos',
  getParentRoute: () => DiagnosticoRouteRoute,
} as any)
const DiagnosticoCalorRoute = DiagnosticoCalorRouteImport.update({
  id: '/calor',
  path: '/calor',
  getParentRoute: () => DiagnosticoRouteRoute,
} as any)
const DiagnosticoIdentificacaoRoute =
  DiagnosticoIdentificacaoRouteImport.update({
    id: '/identificacao',
    path: '/identificacao',
    getParentRoute: () => DiagnosticoRouteRoute,
  } as any)
const DiagnosticoPendenciasRoute = DiagnosticoPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => DiagnosticoRouteRoute,
} as any)
const DiagnosticoProcuracaoRoute = DiagnosticoProcuracaoRouteImport.update({
  id: '/procuracao',
  path: '/procuracao',
  getParentRoute: () => DiagnosticoRouteRoute,
} as any)
const DiagnosticoRevisaoRoute = DiagnosticoRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => DiagnosticoRouteRoute,
} as any)
const DiagnosticoRiscosRoute = DiagnosticoRiscosRouteImport.update({
  id: '/riscos',
  path: '/riscos',
  getParentRoute: () => DiagnosticoRouteRoute,
} as any)
const DiagnosticoSituacaoRoute = DiagnosticoSituacaoRouteImport.update({
  id: '/situacao',
  path: '/situacao',
  getParentRoute: () => DiagnosticoRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoEnviadoProtocoloRoute =
  DiagnosticoEnviadoProtocoloRouteImport.update({
    id: '/enviado/$protocolo',
    path: '/enviado/$protocolo',
    getParentRoute: () => DiagnosticoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/diagnostico/anexos': typeof DiagnosticoAnexosRoute
  '/diagnostico/calor': typeof DiagnosticoCalorRoute
  '/diagnostico/identificacao': typeof DiagnosticoIdentificacaoRoute
  '/diagnostico/pendencias': typeof DiagnosticoPendenciasRoute
  '/diagnostico/procuracao': typeof DiagnosticoProcuracaoRoute
  '/diagnostico/revisao': typeof DiagnosticoRevisaoRoute
  '/diagnostico/riscos': typeof DiagnosticoRiscosRoute
  '/diagnostico/situacao': typeof DiagnosticoSituacaoRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/diagnostico/enviado/$protocolo': typeof DiagnosticoEnviadoProtocoloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/diagnostico/anexos': typeof DiagnosticoAnexosRoute
  '/diagnostico/calor': typeof DiagnosticoCalorRoute
  '/diagnostico/identificacao': typeof DiagnosticoIdentificacaoRoute
  '/diagnostico/pendencias': typeof DiagnosticoPendenciasRoute
  '/diagnostico/procuracao': typeof DiagnosticoProcuracaoRoute
  '/diagnostico/revisao': typeof DiagnosticoRevisaoRoute
  '/diagnostico/riscos': typeof DiagnosticoRiscosRoute
  '/diagnostico/situacao': typeof DiagnosticoSituacaoRoute
  '/diagnostico': typeof DiagnosticoIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/diagnostico/enviado/$protocolo': typeof DiagnosticoEnviadoProtocoloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/diagnostico/anexos': typeof DiagnosticoAnexosRoute
  '/diagnostico/calor': typeof DiagnosticoCalorRoute
  '/diagnostico/identificacao': typeof DiagnosticoIdentificacaoRoute
  '/diagnostico/pendencias': typeof DiagnosticoPendenciasRoute
  '/diagnostico/procuracao': typeof DiagnosticoProcuracaoRoute
  '/diagnostico/revisao': typeof DiagnosticoRevisaoRoute
  '/diagnostico/riscos': typeof DiagnosticoRiscosRoute
  '/diagnostico/situacao': typeof DiagnosticoSituacaoRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/diagnostico/enviado/$protocolo': typeof DiagnosticoEnviadoProtocoloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostico'
    | '/api/$'
    | '/diagnostico/anexos'
    | '/diagnostico/calor'
    | '/diagnostico/identificacao'
    | '/diagnostico/pendencias'
    | '/diagnostico/procuracao'
    | '/diagnostico/revisao'
    | '/diagnostico/riscos'
    | '/diagnostico/situacao'
    | '/diagnostico/'
    | '/api/rpc/$'
    | '/api/trpc/$'
    | '/diagnostico/enviado/$protocolo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/diagnostico/anexos'
    | '/diagnostico/calor'
    | '/diagnostico/identificacao'
    | '/diagnostico/pendencias'
    | '/diagnostico/procuracao'
    | '/diagnostico/revisao'
    | '/diagnostico/riscos'
    | '/diagnostico/situacao'
    | '/diagnostico'
    | '/api/rpc/$'
    | '/api/trpc/$'
    | '/diagnostico/enviado/$protocolo'
  id:
    | '__root__'
    | '/'
    | '/diagnostico'
    | '/api/$'
    | '/diagnostico/anexos'
    | '/diagnostico/calor'
    | '/diagnostico/identificacao'
    | '/diagnostico/pendencias'
    | '/diagnostico/procuracao'
    | '/diagnostico/revisao'
    | '/diagnostico/riscos'
    | '/diagnostico/situacao'
    | '/diagnostico/'
    | '/api/rpc/$'
    | '/api/trpc/$'
    | '/diagnostico/enviado/$protocolo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticoRouteRoute: typeof DiagnosticoRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/': {
      id: '/diagnostico/'
      path: '/'
      fullPath: '/diagnostico/'
      preLoaderRoute: typeof DiagnosticoIndexRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/diagnostico/anexos': {
      id: '/diagnostico/anexos'
      path: '/anexos'
      fullPath: '/diagnostico/anexos'
      preLoaderRoute: typeof DiagnosticoAnexosRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/diagnostico/calor': {
      id: '/diagnostico/calor'
      path: '/calor'
      fullPath: '/diagnostico/calor'
      preLoaderRoute: typeof DiagnosticoCalorRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/diagnostico/identificacao': {
      id: '/diagnostico/identificacao'
      path: '/identificacao'
      fullPath: '/diagnostico/identificacao'
      preLoaderRoute: typeof DiagnosticoIdentificacaoRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/diagnostico/pendencias': {
      id: '/diagnostico/pendencias'
      path: '/pendencias'
      fullPath: '/diagnostico/pendencias'
      preLoaderRoute: typeof DiagnosticoPendenciasRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/diagnostico/procuracao': {
      id: '/diagnostico/procuracao'
      path: '/procuracao'
      fullPath: '/diagnostico/procuracao'
      preLoaderRoute: typeof DiagnosticoProcuracaoRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/diagnostico/revisao': {
      id: '/diagnostico/revisao'
      path: '/revisao'
      fullPath: '/diagnostico/revisao'
      preLoaderRoute: typeof DiagnosticoRevisaoRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/diagnostico/riscos': {
      id: '/diagnostico/riscos'
      path: '/riscos'
      fullPath: '/diagnostico/riscos'
      preLoaderRoute: typeof DiagnosticoRiscosRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/diagnostico/situacao': {
      id: '/diagnostico/situacao'
      path: '/situacao'
      fullPath: '/diagnostico/situacao'
      preLoaderRoute: typeof DiagnosticoSituacaoRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/enviado/$protocolo': {
      id: '/diagnostico/enviado/$protocolo'
      path: '/enviado/$protocolo'
      fullPath: '/diagnostico/enviado/$protocolo'
      preLoaderRoute: typeof DiagnosticoEnviadoProtocoloRouteImport
      parentRoute: typeof DiagnosticoRouteRoute
    }
  }
}

interface DiagnosticoRouteRouteChildren {
  DiagnosticoAnexosRoute: typeof DiagnosticoAnexosRoute
  DiagnosticoCalorRoute: typeof DiagnosticoCalorRoute
  DiagnosticoIdentificacaoRoute: typeof DiagnosticoIdentificacaoRoute
  DiagnosticoPendenciasRoute: typeof DiagnosticoPendenciasRoute
  DiagnosticoProcuracaoRoute: typeof DiagnosticoProcuracaoRoute
  DiagnosticoRevisaoRoute: typeof DiagnosticoRevisaoRoute
  DiagnosticoRiscosRoute: typeof DiagnosticoRiscosRoute
  DiagnosticoSituacaoRoute: typeof DiagnosticoSituacaoRoute
  DiagnosticoIndexRoute: typeof DiagnosticoIndexRoute
  DiagnosticoEnviadoProtocoloRoute: typeof DiagnosticoEnviadoProtocoloRoute
}

const DiagnosticoRouteRouteChildren: DiagnosticoRouteRouteChildren = {
  DiagnosticoAnexosRoute: DiagnosticoAnexosRoute,
  DiagnosticoCalorRoute: DiagnosticoCalorRoute,
  DiagnosticoIdentificacaoRoute: DiagnosticoIdentificacaoRoute,
  DiagnosticoPendenciasRoute: DiagnosticoPendenciasRoute,
  DiagnosticoProcuracaoRoute: DiagnosticoProcuracaoRoute,
  DiagnosticoRevisaoRoute: DiagnosticoRevisaoRoute,
  DiagnosticoRiscosRoute: DiagnosticoRiscosRoute,
  DiagnosticoSituacaoRoute: DiagnosticoSituacaoRoute,
  DiagnosticoIndexRoute: DiagnosticoIndexRoute,
  DiagnosticoEnviadoProtocoloRoute: DiagnosticoEnviadoProtocoloRoute,
}

const DiagnosticoRouteRouteWithChildren =
  DiagnosticoRouteRoute._addFileChildren(DiagnosticoRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticoRouteRoute: DiagnosticoRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
